# Generated by Django 3.1.7 on 2021-03-25 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('khana', '0008_tempuser_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 6, 38, 26, 365896, tzinfo=utc)),
        ),
    ]
