# Generated by Django 3.1.7 on 2021-03-25 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('khana', '0009_auto_20210325_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 6, 39, 49, 17696, tzinfo=utc)),
        ),
    ]
