# Generated by Django 3.1.7 on 2021-03-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khana', '0011_auto_20210325_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
